// Code generated by hand for custom builds.
// This file is compiled only in the custom game build (-tags custom).

//go:build custom

package partner

import (
	"github.com/Team254/cheesy-arena/model"
)

const (
	AvatarsDir = "static/img/avatars"
)

type TbaClient struct {
	BaseUrl string
}

type TbaTeam struct {
	TeamNumber int    `json:"team_number"`
	Name       string `json:"name"`
	Nickname   string `json:"nickname"`
	City       string `json:"city"`
	StateProv  string `json:"state_prov"`
	Country    string `json:"country"`
	RookieYear int    `json:"rookie_year"`
}

type TbaAward struct {
	Name      string `json:"name"`
	EventKey  string `json:"event_key"`
	Year      int    `json:"year"`
	EventName string
}

func NewTbaClient(eventCode, secretId, secret string) *TbaClient {
	return &TbaClient{}
}

func (client *TbaClient) GetTeam(teamNumber int) (*TbaTeam, error) {
	return &TbaTeam{}, nil
}

func (client *TbaClient) GetRobotName(teamNumber int, year int) (string, error) {
	return "", nil
}

func (client *TbaClient) GetTeamAwards(teamNumber int) ([]*TbaAward, error) {
	return nil, nil
}

func (client *TbaClient) DownloadTeamAvatar(teamNumber, year int) error {
	return nil
}

func (client *TbaClient) PublishTeams(database *model.Database) error {
	return nil
}

func (client *TbaClient) PublishMatches(database *model.Database) error {
	return nil
}

func (client *TbaClient) PublishRankings(database *model.Database) error {
	return nil
}

func (client *TbaClient) PublishAlliances(database *model.Database) error {
	return nil
}

func (client *TbaClient) PublishAwards(database *model.Database) error {
	return nil
}

func (client *TbaClient) DeletePublishedMatches() error {
	return nil
}
