// Code generator module for emitting game/generated_score_test.go, which contains
// automated tests validating point calculations, statuses, fouls, and ranking sorting.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func generateScoreTest(yamlData *GameYAML, destDir string) error {
	filePath := filepath.Join(destDir, "generated_score_test.go")

	var sb strings.Builder
	sb.WriteString(`// Code generated by cmd/generate from game/game.yaml. DO NOT EDIT.
// Regenerate: go generate ./generate/

//go:build custom

package game

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

`)

	// 1. Zero Score Test
	sb.WriteString(`func TestGeneratedSummarize_ZeroScore(t *testing.T) {
	score := &Score{}
	opponent := &Score{}
	summary := score.Summarize(opponent)
	assert.Equal(t, 0, summary.AutoPoints)
	assert.Equal(t, 0, summary.TeleopPoints)
	assert.Equal(t, 0, summary.EndgamePoints)
	assert.Equal(t, 0, summary.MatchPoints)
	assert.Equal(t, 0, summary.FoulPoints)
	assert.Equal(t, 0, summary.Score)
`)
	for _, sc := range yamlData.ScoringCounts {
		sb.WriteString(fmt.Sprintf("\tassert.Equal(t, 0, summary.%sPoints)\n", toCamelCase(sc.ID)))
	}
	for _, ec := range yamlData.EndgameCounts {
		sb.WriteString(fmt.Sprintf("\tassert.Equal(t, 0, summary.%sPoints)\n", toCamelCase(ec.ID)))
	}
	for _, status := range yamlData.Statuses {
		sb.WriteString(fmt.Sprintf("\tassert.Equal(t, 0, summary.%sPoints)\n", toCamelCase(status.ID)))
	}
	sb.WriteString("}\n\n")

	// 2. Per scoring_count element
	for _, sc := range yamlData.ScoringCounts {
		camel := toCamelCase(sc.ID)
		sb.WriteString(fmt.Sprintf("func TestGeneratedSummarize_%s(t *testing.T) {\n", camel))
		if sc.Phase == "auto" || sc.Phase == "both" {
			sb.WriteString(fmt.Sprintf(`	// Auto phase
	{
		score := &Score{Auto%sCount: 3}
		summary := score.Summarize(&Score{})
		assert.Equal(t, 3*%sAutoPointsVal, summary.%sPoints)
		assert.Equal(t, 3*%sAutoPointsVal, summary.AutoPoints)
		assert.Equal(t, 0, summary.TeleopPoints)
	}
`, camel, camel, camel, camel))
		}
		if sc.Phase == "teleop" || sc.Phase == "both" {
			sb.WriteString(fmt.Sprintf(`	// Teleop phase
	{
		score := &Score{Teleop%sCount: 2}
		summary := score.Summarize(&Score{})
		assert.Equal(t, 2*%sTeleopPointsVal, summary.%sPoints)
		assert.Equal(t, 0, summary.AutoPoints)
		assert.Equal(t, 2*%sTeleopPointsVal, summary.TeleopPoints)
	}
`, camel, camel, camel, camel))
		}
		sb.WriteString("}\n\n")
	}

	// 3. Per endgame_count element
	for _, ec := range yamlData.EndgameCounts {
		camel := toCamelCase(ec.ID)
		sb.WriteString(fmt.Sprintf(`func TestGeneratedSummarize_%s(t *testing.T) {
	score := &Score{Endgame%sCount: 2}
	summary := score.Summarize(&Score{})
	assert.Equal(t, 2*%sEndgamePointsVal, summary.%sPoints)
	assert.Equal(t, 2*%sEndgamePointsVal, summary.EndgamePoints)
	assert.Equal(t, 0, summary.AutoPoints)
}

`, camel, camel, camel, camel, camel))
	}

	// 4 & 5. Per status
	for _, status := range yamlData.Statuses {
		camel := toCamelCase(status.ID)
		sb.WriteString(fmt.Sprintf("func TestGeneratedSummarize_%s(t *testing.T) {\n", camel))

		var rollupField string
		if status.Phase == "auto" {
			rollupField = "AutoPoints"
		} else {
			rollupField = "EndgamePoints"
		}

		if len(status.Values) >= 2 {
			// Enum status: test each non-zero value
			for i := 1; i < len(status.Values); i++ {
				val := status.Values[i]
				valCamel := toCamelCase(val.ID)
				zeroValCamel := toCamelCase(status.Values[0].ID)
				sb.WriteString(fmt.Sprintf(`	{
		score := &Score{%sStatuses: [3]%sStatus{%s%s, %s%s, %s%s}}
		summary := score.Summarize(&Score{})
		assert.Equal(t, %s%sPointsVal, summary.%sPoints)
		assert.Equal(t, %s%sPointsVal, summary.%s)
	}
`, camel, camel, camel, valCamel, camel, zeroValCamel, camel, zeroValCamel, camel, valCamel, camel, camel, valCamel, rollupField))
			}
		} else {
			// Bool status: test 1 and 3 robots
			sb.WriteString(fmt.Sprintf(`	// 1 robot
	{
		score := &Score{%sStatuses: [3]bool{true, false, false}}
		summary := score.Summarize(&Score{})
		assert.Equal(t, %sPointsVal, summary.%sPoints)
		assert.Equal(t, %sPointsVal, summary.%s)
	}
	// 3 robots
	{
		score := &Score{%sStatuses: [3]bool{true, true, true}}
		summary := score.Summarize(&Score{})
		assert.Equal(t, 3*%sPointsVal, summary.%sPoints)
		assert.Equal(t, 3*%sPointsVal, summary.%s)
	}
`, camel, camel, camel, camel, rollupField, camel, camel, camel, camel, rollupField))
		}
		sb.WriteString("}\n\n")
	}

	// 6. Foul points
	sb.WriteString(`func TestGeneratedSummarize_FoulPoints(t *testing.T) {
	score := &Score{}
	opponent := &Score{Fouls: []Foul{
		{IsMajor: false},
		{IsMajor: true},
	}}
	summary := score.Summarize(opponent)
	assert.Equal(t, MinorFoulPoints+MajorFoulPoints, summary.FoulPoints)
	assert.Equal(t, 1, summary.NumOpponentMajorFouls)
	assert.Equal(t, MinorFoulPoints+MajorFoulPoints, summary.Score)
}

`)

	// 7. Playoff tiebreakers
	// Major fouls tiebreaker (implicit)
	sb.WriteString(`func TestGeneratedDetermineMatchStatus_MajorFoulsTiebreak(t *testing.T) {
	red := &ScoreSummary{Score: 10, NumOpponentMajorFouls: 2}
	blue := &ScoreSummary{Score: 10, NumOpponentMajorFouls: 0}
	status, label := DetermineMatchStatus(red, blue, true)
	assert.Equal(t, RedWonMatch, status)
	assert.Equal(t, "TIEBREAK: MAJOR FOULS", label)
}

`)

	for _, tb := range yamlData.PlayoffTiebreakers {
		var ownField, label string
		switch tb.Metric {
		case "auto_points":
			ownField = "AutoPoints"
			label = "AUTO POINTS"
		case "teleop_points":
			ownField = "TeleopPoints"
			label = "TELEOP POINTS"
		case "endgame_points":
			ownField = "EndgamePoints"
			label = "ENDGAME POINTS"
		case "total_points":
			ownField = "MatchPoints"
			label = "TOTAL POINTS"
		default:
			ownField = toCamelCase(tb.Metric) + "Points"
			displayName := tb.Metric
			for _, sc := range yamlData.ScoringCounts {
				if sc.ID == tb.Metric {
					displayName = sc.DisplayName
				}
			}
			for _, ec := range yamlData.EndgameCounts {
				if ec.ID == tb.Metric {
					displayName = ec.DisplayName
				}
			}
			for _, s := range yamlData.Statuses {
				if s.ID == tb.Metric {
					displayName = s.DisplayName
				}
			}
			label = strings.ToUpper(displayName)
		}

		sb.WriteString(fmt.Sprintf(`func TestGeneratedDetermineMatchStatus_%sTiebreak(t *testing.T) {
	red := &ScoreSummary{Score: 10, %s: 8}
	blue := &ScoreSummary{Score: 10, %s: 4}
	status, label := DetermineMatchStatus(red, blue, true)
	assert.Equal(t, RedWonMatch, status)
	assert.Equal(t, "TIEBREAK: %s", label)
}

`, toCamelCase(tb.Metric), ownField, ownField, label))
	}

	// 8. Ranking Less tiebreaker order cascade
	// Generate Tier 0 first (RankingPoints)
	sb.WriteString(`func TestGeneratedRankingLess_Tier0_RankingPoints(t *testing.T) {
	a := Ranking{TeamId: 1, RankingFields: RankingFields{RankingPoints: 10, Played: 3}}
	b := Ranking{TeamId: 2, RankingFields: RankingFields{RankingPoints: 5, Played: 3}}
	rankings := Rankings{a, b}
	assert.True(t, rankings.Less(0, 1))
	assert.False(t, rankings.Less(1, 0))
}

`)

	// Cascade configuration
	// We build up the base values for fields that are equal, in order so the
	// generated output is deterministic across runs (maps randomise iteration).
	type equalField struct {
		name string
		val  int
	}
	var equalFields []equalField

	for idx, tb := range yamlData.RankingTiebreakers {
		var fieldName string
		switch tb.Metric {
		case "auto_points":
			fieldName = "AutoPoints"
		case "teleop_points":
			fieldName = "TeleopPoints"
		case "endgame_points":
			fieldName = "EndgamePoints"
		case "total_points":
			fieldName = "MatchPoints"
		default:
			fieldName = toCamelCase(tb.Metric) + "Points"
		}

		tierNum := idx + 1
		sb.WriteString(fmt.Sprintf("func TestGeneratedRankingLess_Tier%d_%s(t *testing.T) {\n", tierNum, fieldName))
		sb.WriteString("\ta := Ranking{TeamId: 1, RankingFields: RankingFields{\n")
		sb.WriteString("\t\tRankingPoints: 9,\n")
		for _, ef := range equalFields {
			sb.WriteString(fmt.Sprintf("\t\t%s: %d,\n", ef.name, ef.val))
		}
		sb.WriteString(fmt.Sprintf("\t\t%s: 50,\n", fieldName))
		sb.WriteString("\t\tPlayed: 3,\n\t}}\n")

		sb.WriteString("\tb := Ranking{TeamId: 2, RankingFields: RankingFields{\n")
		sb.WriteString("\t\tRankingPoints: 9,\n")
		for _, ef := range equalFields {
			sb.WriteString(fmt.Sprintf("\t\t%s: %d,\n", ef.name, ef.val))
		}
		sb.WriteString(fmt.Sprintf("\t\t%s: 30,\n", fieldName))
		sb.WriteString("\t\tPlayed: 3,\n\t}}\n")

		sb.WriteString(`	rankings := Rankings{a, b}
	assert.True(t, rankings.Less(0, 1))
	assert.False(t, rankings.Less(1, 0))
}

`)

		// Append in order for the next tier (deterministic, unlike a map)
		equalFields = append(equalFields, equalField{name: fieldName, val: 100})
	}

	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}
