// Code generator module for emitting game/generated_constants.go, which defines
// game-wide metadata, mode flags, and foul point values based on game.yaml configuration.

package main

import (
	"fmt"
	"os"
	"path/filepath"
)

func generateConstants(yamlData *GameYAML, destDir string) error {
	filePath := filepath.Join(destDir, "generated_constants.go")
	content := fmt.Sprintf(`// Code generated by cmd/generate from game/game.yaml. DO NOT EDIT.
// Regenerate: go generate ./generate/

//go:build custom

package game

const CustomGameMode = true
const CustomGameName = %q

// Custom games do not use Hub shift timing; suppresses shift_change sound cues.
const UseShifts = false

// Foul points (custom game may differ from standard FRC).
// These are referenced by foul.go (untagged) so must live here, not in generated_score_summary.go.
const MinorFoulPoints = %d
const MajorFoulPoints = %d
`, yamlData.Game.Name, yamlData.Fouls.MinorFoulPoints, yamlData.Fouls.MajorFoulPoints)

	return os.WriteFile(filePath, []byte(content), 0644)
}
