// Code generator module for emitting game/generated_score.go, which defines
// the dynamic Score struct and its field comparison (Equals method).

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func generateScore(yamlData *GameYAML, destDir string) error {
	filePath := filepath.Join(destDir, "generated_score.go")

	var sb strings.Builder
	sb.WriteString(`// Code generated by cmd/generate from game/game.yaml. DO NOT EDIT.
// Regenerate: go generate ./generate/

//go:build custom

package game

`)

	// Enum status types and values
	for _, status := range yamlData.Statuses {
		if len(status.Values) >= 2 {
			camelStatus := toCamelCase(status.ID)
			sb.WriteString(fmt.Sprintf("type %sStatus int\n\nconst (\n", camelStatus))
			for i, val := range status.Values {
				sb.WriteString(fmt.Sprintf("\t%s%s", camelStatus, toCamelCase(val.ID)))
				if i == 0 {
					sb.WriteString(fmt.Sprintf(" %sStatus = iota\n", camelStatus))
				} else {
					sb.WriteString("\n")
				}
			}
			sb.WriteString(")\n\n")
		}
	}

	sb.WriteString(`// Score holds the instantaneous scoring state for one alliance.
type Score struct {
	`)

	// scoring_counts
	for _, sc := range yamlData.ScoringCounts {
		camel := toCamelCase(sc.ID)
		if sc.Phase == "auto" || sc.Phase == "both" {
			sb.WriteString(fmt.Sprintf("\tAuto%sCount int\n", camel))
		}
		if sc.Phase == "teleop" || sc.Phase == "both" {
			sb.WriteString(fmt.Sprintf("\tTeleop%sCount int\n", camel))
		}
	}
	if len(yamlData.ScoringCounts) > 0 {
		sb.WriteString("\n")
	}

	// endgame_counts
	for _, ec := range yamlData.EndgameCounts {
		camel := toCamelCase(ec.ID)
		sb.WriteString(fmt.Sprintf("\tEndgame%sCount int\n", camel))
	}
	if len(yamlData.EndgameCounts) > 0 {
		sb.WriteString("\n")
	}

	// statuses
	for _, status := range yamlData.Statuses {
		camel := toCamelCase(status.ID)
		if len(status.Values) >= 2 {
			sb.WriteString(fmt.Sprintf("\t%sStatuses [3]%sStatus\n", camel, camel))
		} else {
			sb.WriteString(fmt.Sprintf("\t%sStatuses [3]bool\n", camel))
		}
	}
	if len(yamlData.Statuses) > 0 {
		sb.WriteString("\n")
	}

	// Always present fields and Hub
	sb.WriteString("\tFouls     []Foul\n\tPlayoffDq bool\n\n\t// Hub is always included because arena.go and team_sign.go access CurrentScore.Hub\n\t// directly without build tags. hub.go is untagged so Hub is available in both builds.\n\t// In the custom build, Hub is never populated (UpdateState is never called) — all\n\t// Hub methods return 0/false.\n\tHub Hub\n}\n\n")

	// Equals method
	sb.WriteString("func (score *Score) Equals(other *Score) bool {\n")
	var checks []string

	for _, sc := range yamlData.ScoringCounts {
		camel := toCamelCase(sc.ID)
		if sc.Phase == "auto" || sc.Phase == "both" {
			checks = append(checks, fmt.Sprintf("score.Auto%sCount != other.Auto%sCount", camel, camel))
		}
		if sc.Phase == "teleop" || sc.Phase == "both" {
			checks = append(checks, fmt.Sprintf("score.Teleop%sCount != other.Teleop%sCount", camel, camel))
		}
	}
	for _, ec := range yamlData.EndgameCounts {
		camel := toCamelCase(ec.ID)
		checks = append(checks, fmt.Sprintf("score.Endgame%sCount != other.Endgame%sCount", camel, camel))
	}
	for _, status := range yamlData.Statuses {
		camel := toCamelCase(status.ID)
		checks = append(checks, fmt.Sprintf("score.%sStatuses != other.%sStatuses", camel, camel))
	}
	checks = append(checks, "score.PlayoffDq != other.PlayoffDq")
	checks = append(checks, "len(score.Fouls) != len(other.Fouls)")

	sb.WriteString("\tif ")
	sb.WriteString(strings.Join(checks, " ||\n\t\t"))
	sb.WriteString(" {\n\t\treturn false\n\t}\n")

	sb.WriteString(`	for i, foul := range score.Fouls {
		if foul != other.Fouls[i] {
			return false
		}
	}
	return true
}
`)

	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}
