// Code generators for the test files: game/generated_score_test.go (scoring/ranking assertions)
// and cmd/generate/generated_template_test.go (the rendered templates parse + contain the expected
// per-element markup). Kept separate from the Go (codegen_go.go) and web (codegen_web.go) generators.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func generateScoreTest(yamlData *GameYAML, destDir string) error {
	filePath := filepath.Join(destDir, "generated_score_test.go")

	var sb strings.Builder
	sb.WriteString(`// Code generated by cmd/generate from game/custom_game.yaml. DO NOT EDIT.
// Regenerate: go generate ./...

//go:build custom

package game

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

`)

	// 1. Zero Score Test
	sb.WriteString(`func TestGeneratedSummarize_ZeroScore(t *testing.T) {
	score := &Score{}
	opponent := &Score{}
	summary := score.Summarize(opponent)
	assert.Equal(t, 0, summary.AutoPoints)
	assert.Equal(t, 0, summary.TeleopPoints)
	assert.Equal(t, 0, summary.EndgamePoints)
	assert.Equal(t, 0, summary.MatchPoints)
	assert.Equal(t, 0, summary.FoulPoints)
	assert.Equal(t, 0, summary.Score)
`)
	for _, sc := range yamlData.ScoringCounts {
		sb.WriteString(fmt.Sprintf("\tassert.Equal(t, 0, summary.%sPoints)\n", toCamelCase(sc.ID)))
	}
	for _, status := range yamlData.Statuses {
		sb.WriteString(fmt.Sprintf("\tassert.Equal(t, 0, summary.%sPoints)\n", toCamelCase(status.ID)))
	}
	sb.WriteString("}\n\n")

	// 2. Per scoring_count element — one sub-test block per declared phase, asserting that
	// every other phase's accumulator stays at 0 when only this phase's count is set.
	phaseAccumField := map[string]string{"auto": "AutoPoints", "teleop": "TeleopPoints", "endgame": "EndgamePoints"}
	allPhases := []string{"auto", "teleop", "endgame"}
	for _, sc := range yamlData.ScoringCounts {
		camel := toCamelCase(sc.ID)
		sb.WriteString(fmt.Sprintf("func TestGeneratedSummarize_%s(t *testing.T) {\n", camel))
		for _, ep := range sc.Phases {
			prefix := phaseFieldPrefix[ep.Phase]
			accumField := phaseAccumField[ep.Phase]
			sb.WriteString(fmt.Sprintf(`	// %s phase
	{
		score := &Score{%s%sCount: 3}
		summary := score.Summarize(&Score{})
		assert.Equal(t, 3*%s%sPointsVal, summary.%sPoints)
		assert.Equal(t, 3*%s%sPointsVal, summary.%s)
`, phaseSectionTitle[ep.Phase], prefix, camel, camel, prefix, camel, camel, prefix, accumField))
			for _, otherPhase := range allPhases {
				if !sc.HasPhase(otherPhase) {
					sb.WriteString(fmt.Sprintf("\t\tassert.Equal(t, 0, summary.%s)\n", phaseAccumField[otherPhase]))
				}
			}
			sb.WriteString("\t}\n")
		}
		sb.WriteString("}\n\n")
	}

	// 3 & 4. Per status
	for _, status := range yamlData.Statuses {
		camel := toCamelCase(status.ID)
		sb.WriteString(fmt.Sprintf("func TestGeneratedSummarize_%s(t *testing.T) {\n", camel))

		rollupField := phaseAccumField[status.Phases[0].Phase]

		if len(status.Values) >= 2 {
			// Enum status: test each non-zero value
			for i := 1; i < len(status.Values); i++ {
				val := status.Values[i]
				valCamel := toCamelCase(val.ID)
				zeroValCamel := toCamelCase(status.Values[0].ID)
				sb.WriteString(fmt.Sprintf(`	{
		score := &Score{%sStatuses: [3]%sStatus{%s%s, %s%s, %s%s}}
		summary := score.Summarize(&Score{})
		assert.Equal(t, %s%sPointsVal, summary.%sPoints)
		assert.Equal(t, %s%sPointsVal, summary.%s)
	}
`, camel, camel, camel, valCamel, camel, zeroValCamel, camel, zeroValCamel, camel, valCamel, camel, camel, valCamel, rollupField))
			}
		} else {
			// Bool status: test 1 and 3 robots
			sb.WriteString(fmt.Sprintf(`	// 1 robot
	{
		score := &Score{%sStatuses: [3]bool{true, false, false}}
		summary := score.Summarize(&Score{})
		assert.Equal(t, %sPointsVal, summary.%sPoints)
		assert.Equal(t, %sPointsVal, summary.%s)
	}
	// 3 robots
	{
		score := &Score{%sStatuses: [3]bool{true, true, true}}
		summary := score.Summarize(&Score{})
		assert.Equal(t, 3*%sPointsVal, summary.%sPoints)
		assert.Equal(t, 3*%sPointsVal, summary.%s)
	}
`, camel, camel, camel, camel, rollupField, camel, camel, camel, camel, rollupField))
		}
		sb.WriteString("}\n\n")
	}

	// 6. Foul points
	sb.WriteString(`func TestGeneratedSummarize_FoulPoints(t *testing.T) {
	score := &Score{}
	opponent := &Score{Fouls: []Foul{
		{IsMajor: false},
		{IsMajor: true},
	}}
	summary := score.Summarize(opponent)
	assert.Equal(t, MinorFoulPoints+MajorFoulPoints, summary.FoulPoints)
	assert.Equal(t, 1, summary.NumOpponentMajorFouls)
	assert.Equal(t, MinorFoulPoints+MajorFoulPoints, summary.Score)
}

`)

	// 7. Playoff tiebreakers
	// Major fouls tiebreaker (implicit)
	sb.WriteString(`func TestGeneratedDetermineMatchStatus_MajorFoulsTiebreak(t *testing.T) {
	red := &ScoreSummary{Score: 10, NumOpponentMajorFouls: 2}
	blue := &ScoreSummary{Score: 10, NumOpponentMajorFouls: 0}
	status, label := DetermineMatchStatus(red, blue, true)
	assert.Equal(t, RedWonMatch, status)
	assert.Equal(t, "TIEBREAK: MAJOR FOULS", label)
}

`)

	for _, tb := range yamlData.PlayoffTiebreakers {
		var ownField, label string
		switch tb.Metric {
		case "auto_points":
			ownField = "AutoPoints"
			label = "AUTO POINTS"
		case "teleop_points":
			ownField = "TeleopPoints"
			label = "TELEOP POINTS"
		case "endgame_points":
			ownField = "EndgamePoints"
			label = "ENDGAME POINTS"
		case "total_points":
			ownField = "MatchPoints"
			label = "TOTAL POINTS"
		default:
			ownField = toCamelCase(tb.Metric) + "Points"
			displayName := tb.Metric
			for _, sc := range yamlData.ScoringCounts {
				if sc.ID == tb.Metric {
					displayName = sc.DisplayName
				}
			}
			for _, s := range yamlData.Statuses {
				if s.ID == tb.Metric {
					displayName = s.DisplayName
				}
			}
			label = strings.ToUpper(displayName)
		}

		sb.WriteString(fmt.Sprintf(`func TestGeneratedDetermineMatchStatus_%sTiebreak(t *testing.T) {
	red := &ScoreSummary{Score: 10, %s: 8}
	blue := &ScoreSummary{Score: 10, %s: 4}
	status, label := DetermineMatchStatus(red, blue, true)
	assert.Equal(t, RedWonMatch, status)
	assert.Equal(t, "TIEBREAK: %s", label)
}

`, toCamelCase(tb.Metric), ownField, ownField, label))
	}

	// 8. Ranking Less tiebreaker order cascade
	// Generate Tier 0 first (RankingPoints)
	sb.WriteString(`func TestGeneratedRankingLess_Tier0_RankingPoints(t *testing.T) {
	a := Ranking{TeamId: 1, RankingFields: RankingFields{RankingPoints: 10, Played: 3}}
	b := Ranking{TeamId: 2, RankingFields: RankingFields{RankingPoints: 5, Played: 3}}
	rankings := Rankings{a, b}
	assert.True(t, rankings.Less(0, 1))
	assert.False(t, rankings.Less(1, 0))
}

`)

	// Cascade configuration
	// We build up the base values for fields that are equal, in order so the
	// generated output is deterministic across runs (maps randomise iteration).
	type equalField struct {
		name string
		val  int
	}
	var equalFields []equalField

	for idx, tb := range yamlData.RankingTiebreakers {
		var fieldName string
		switch tb.Metric {
		case "auto_points":
			fieldName = "AutoPoints"
		case "teleop_points":
			fieldName = "TeleopPoints"
		case "endgame_points":
			fieldName = "EndgamePoints"
		case "total_points":
			fieldName = "MatchPoints"
		default:
			fieldName = toCamelCase(tb.Metric) + "Points"
		}

		tierNum := idx + 1
		sb.WriteString(fmt.Sprintf("func TestGeneratedRankingLess_Tier%d_%s(t *testing.T) {\n", tierNum, fieldName))
		sb.WriteString("\ta := Ranking{TeamId: 1, RankingFields: RankingFields{\n")
		sb.WriteString("\t\tRankingPoints: 9,\n")
		for _, ef := range equalFields {
			sb.WriteString(fmt.Sprintf("\t\t%s: %d,\n", ef.name, ef.val))
		}
		sb.WriteString(fmt.Sprintf("\t\t%s: 50,\n", fieldName))
		sb.WriteString("\t\tPlayed: 3,\n\t}}\n")

		sb.WriteString("\tb := Ranking{TeamId: 2, RankingFields: RankingFields{\n")
		sb.WriteString("\t\tRankingPoints: 9,\n")
		for _, ef := range equalFields {
			sb.WriteString(fmt.Sprintf("\t\t%s: %d,\n", ef.name, ef.val))
		}
		sb.WriteString(fmt.Sprintf("\t\t%s: 30,\n", fieldName))
		sb.WriteString("\t\tPlayed: 3,\n\t}}\n")

		sb.WriteString(`	rankings := Rankings{a, b}
	assert.True(t, rankings.Less(0, 1))
	assert.False(t, rankings.Less(1, 0))
}

`)

		// Append in order for the next tier (deterministic, unlike a map)
		equalFields = append(equalFields, equalField{name: fieldName, val: 100})
	}

	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func generateTemplateTest(yamlData *GameYAML, destDir string) error {
	filePath := filepath.Join(destDir, "generated_template_test.go")

	var sb strings.Builder
	sb.WriteString(`// Code generated by cmd/generate from game/custom_game.yaml. DO NOT EDIT.
// Regenerate: go generate ./...

package main

import (
	"html/template"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestGeneratedTemplates_ParseAndContent(t *testing.T) {
	templatesDir := "../../templates"
	panelPath := filepath.Join(templatesDir, "generated_scoring_panel.html")
	audiencePath := filepath.Join(templatesDir, "generated_audience_display.html")

	{
		content, err := os.ReadFile(panelPath)
		assert.NoError(t, err)
		tmpl := template.New("scoring")
		tmpl.Funcs(template.FuncMap{
			"dict": func(values ...any) (map[string]any, error) { return nil, nil },
			"seq": func(n int) []int { return []int{0, 1, 2} },
			"add": func(a, b int) int { return a + b },
		})
		_, err = tmpl.Parse(string(content))
		assert.NoError(t, err)

`)

	for _, sc := range yamlData.ScoringCounts {
		for _, ep := range sc.Phases {
			sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`onclick="adjustCount('%s', '%s', -1);"`, sc.ID, ep.Phase)))
			sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`id="%s-%s-count"`, sc.ID, ep.Phase)))
		}
	}
	for _, status := range yamlData.Statuses {
		if status.Phases[0].Phase == "auto" {
			if len(status.Values) >= 2 {
				sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`onclick="cycleEnumStatus('%s', {{add $i -1}});"`, status.ID)))
			} else {
				sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`onclick="toggleBoolStatus('%s', {{add $i -1}});"`, status.ID)))
			}
		}
	}

	sb.WriteString(`	}

	{
		content, err := os.ReadFile(audiencePath)
		assert.NoError(t, err)
		tmpl := template.New("audience")
		tmpl.Funcs(template.FuncMap{
			"seq": func(n int) []int { return []int{0, 1, 2, 3} },
			"add": func(a, b int) int { return a + b },
		})
		_, err = tmpl.Parse(string(content))
		assert.NoError(t, err)

`)

	displayGroups := buildDisplayGroups(yamlData)

	for _, pg := range displayGroups {
		sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`id="leftFinal%sPoints"`, toCamelCase(pg.ID))))
		sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`id="rightFinal%sPoints"`, toCamelCase(pg.ID))))
	}
	for _, status := range yamlData.Statuses {
		sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`id="leftFinal%sPoints"`, toCamelCase(status.ID))))
	}
	for _, rp := range yamlData.RPs {
		sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`id="leftFinal%sRankingPoint"`, toCamelCase(rp.ID))))
	}

	sb.WriteString(`	}

	{
		refereePath := filepath.Join(templatesDir, "generated_referee_panel.html")
		content, err := os.ReadFile(refereePath)
		assert.NoError(t, err)
		tmpl := template.New("referee")
		tmpl.Funcs(template.FuncMap{
			"dict": func(values ...any) (map[string]any, error) { return nil, nil },
			"seq":  func(n int) []int { return []int{0, 1, 2} },
		})
		_, err = tmpl.Parse(string(content))
		assert.NoError(t, err)

		assert.Contains(t, string(content), "generated_referee_panel.js")
`)

	for _, phase := range []string{"auto", "teleop", "endgame"} {
		hasPhase := false
		for _, sc := range yamlData.ScoringCounts {
			if sc.HasPhase(phase) {
				hasPhase = true
			}
		}
		if hasPhase {
			sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`phase-%s`, phase)))
		}
	}
	for _, status := range yamlData.Statuses {
		sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`team-1-%s`, status.ID)))
	}

	sb.WriteString(`	}
}

func TestGeneratedJS_Content(t *testing.T) {
	jsDir := "../../static/js"
	panelJsPath := filepath.Join(jsDir, "generated_scoring_panel.js")
	audienceJsPath := filepath.Join(jsDir, "generated_audience_display.js")

	{
		content, err := os.ReadFile(panelJsPath)
		assert.NoError(t, err)
		assert.Contains(t, string(content), "adjustCount = function")
		assert.Contains(t, string(content), "toggleBoolStatus = function")
		assert.Contains(t, string(content), "setEnumStatus = function")
		assert.Contains(t, string(content), "cycleEnumStatus = function")
`)

	for _, sc := range yamlData.ScoringCounts {
		camel := toCamelCase(sc.ID)
		for _, ep := range sc.Phases {
			sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`score.%s%sCount`, phaseFieldPrefix[ep.Phase], camel)))
		}
	}

	sb.WriteString(`	}

	{
		content, err := os.ReadFile(audienceJsPath)
		assert.NoError(t, err)
		assert.Contains(t, string(content), "handleRealtimeScoreGenerated = function")
		assert.Contains(t, string(content), "handleScorePostedGenerated = function")
`)

	for _, pg := range displayGroups {
		camelGroup := toCamelCase(pg.ID)
		sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`left%sCount`, camelGroup)))
		sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`leftFinal%sPoints`, camelGroup)))
	}

	sb.WriteString(`	}

	{
		refereeJsPath := filepath.Join(jsDir, "generated_referee_panel.js")
		content, err := os.ReadFile(refereeJsPath)
		assert.NoError(t, err)
		assert.Contains(t, string(content), "updateScoreSummaryGenerated = function")
`)

	for _, phase := range []string{"auto", "teleop", "endgame"} {
		hasPhase := false
		for _, sc := range yamlData.ScoringCounts {
			if sc.HasPhase(phase) {
				hasPhase = true
			}
		}
		if hasPhase {
			sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`phase-%s`, phase)))
			sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`score.%s`, phaseFieldPrefix[phase])))
		}
	}
	for _, status := range yamlData.Statuses {
		sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`team-1-%s`, status.ID)))
		sb.WriteString(fmt.Sprintf("\t\tassert.Contains(t, string(content), %q)\n", fmt.Sprintf(`score.%sStatuses`, toCamelCase(status.ID))))
	}

	sb.WriteString(`	}
}
`)

	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}
