// Code generator module for emitting game/generated_ranking_fields.go, which defines
// custom ranking fields, sorting rules (Less method), and tiebreakers.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func generateRankingFields(yamlData *GameYAML, destDir string) error {
	filePath := filepath.Join(destDir, "generated_ranking_fields.go")

	var sb strings.Builder
	sb.WriteString(`// Code generated by cmd/generate from game/game.yaml. DO NOT EDIT.
// Regenerate: go generate ./generate/

//go:build custom

package game

import "math/rand"

type RankingFields struct {
	RankingPoints int
`)

	for _, tb := range yamlData.RankingTiebreakers {
		var fieldName string
		switch tb.Metric {
		case "auto_points":
			fieldName = "AutoPoints"
		case "teleop_points":
			fieldName = "TeleopPoints"
		case "endgame_points":
			fieldName = "EndgamePoints"
		case "total_points":
			fieldName = "MatchPoints"
		default:
			fieldName = toCamelCase(tb.Metric) + "Points"
		}
		sb.WriteString(fmt.Sprintf("\t%s int\n", fieldName))
	}

	sb.WriteString(`	Random            float64
	Wins              int
	Losses            int
	Ties              int
	Disqualifications int
	Played            int
}

var RankingRandomFloat64 = rand.Float64

func (fields *RankingFields) AddScoreSummary(own, opponent *ScoreSummary, disqualified bool) {
	fields.Played++
	fields.Random = RankingRandomFloat64()
	if disqualified {
		fields.Disqualifications++
		return
	}
	if own.Score > opponent.Score {
		fields.RankingPoints += 3
		fields.Wins++
	} else if own.Score == opponent.Score {
		fields.RankingPoints += 1
		fields.Ties++
	} else {
		fields.Losses++
	}
	fields.RankingPoints += own.BonusRankingPoints
`)

	for _, tb := range yamlData.RankingTiebreakers {
		var fieldName, ownField string
		switch tb.Metric {
		case "auto_points":
			fieldName = "AutoPoints"
			ownField = "AutoPoints"
		case "teleop_points":
			fieldName = "TeleopPoints"
			ownField = "TeleopPoints"
		case "endgame_points":
			fieldName = "EndgamePoints"
			ownField = "EndgamePoints"
		case "total_points":
			fieldName = "MatchPoints"
			ownField = "MatchPoints"
		default:
			fieldName = toCamelCase(tb.Metric) + "Points"
			ownField = toCamelCase(tb.Metric) + "Points"
		}
		sb.WriteString(fmt.Sprintf("\tfields.%s += own.%s\n", fieldName, ownField))
	}

	sb.WriteString("}\n\ntype Ranking struct {\n\tTeamId       int \"db:\\\"id,manual\\\"\"\n\tRank         int\n\tPreviousRank int\n\tRankingFields\n}\n\ntype Rankings []Ranking\n\nfunc (rankings Rankings) Len() int {\n\treturn len(rankings)\n}\n\nfunc (rankings Rankings) Swap(i, j int) {\n\trankings[i], rankings[j] = rankings[j], rankings[i]\n}\n\nfunc (rankings Rankings) Less(i, j int) bool {\n\ta, b := rankings[i], rankings[j]\n\tif a.RankingPoints*b.Played != b.RankingPoints*a.Played {\n\t\treturn a.RankingPoints*b.Played > b.RankingPoints*a.Played\n\t}\n")

	for _, tb := range yamlData.RankingTiebreakers {
		var fieldName string
		switch tb.Metric {
		case "auto_points":
			fieldName = "AutoPoints"
		case "teleop_points":
			fieldName = "TeleopPoints"
		case "endgame_points":
			fieldName = "EndgamePoints"
		case "total_points":
			fieldName = "MatchPoints"
		default:
			fieldName = toCamelCase(tb.Metric) + "Points"
		}
		sb.WriteString(fmt.Sprintf("\tif a.%s*b.Played != b.%s*a.Played {\n", fieldName, fieldName))
		sb.WriteString(fmt.Sprintf("\t\treturn a.%s*b.Played > b.%s*a.Played\n\t}\n", fieldName, fieldName))
	}

	sb.WriteString(`	return a.Random > b.Random
}
`)

	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}
