// Code generator module for emitting game/generated_score_summary.go, which defines
// ScoreSummary, live scoring period accumulations, and match winner tiebreak logic.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func generateScoreSummary(yamlData *GameYAML, destDir string) error {
	filePath := filepath.Join(destDir, "generated_score_summary.go")

	var sb strings.Builder
	sb.WriteString(`// Code generated by cmd/generate from game/game.yaml. DO NOT EDIT.
// Regenerate: go generate ./generate/

//go:build custom

package game

// Per-element point constants (only used in Summarize() below)
const (
`)

	// Constants
	for _, sc := range yamlData.ScoringCounts {
		camel := toCamelCase(sc.ID)
		if sc.Phase == "auto" || sc.Phase == "both" {
			sb.WriteString(fmt.Sprintf("\t%sAutoPointsVal = %d\n", camel, sc.PointsAuto))
		}
		if sc.Phase == "teleop" || sc.Phase == "both" {
			sb.WriteString(fmt.Sprintf("\t%sTeleopPointsVal = %d\n", camel, sc.PointsTeleop))
		}
	}
	for _, ec := range yamlData.EndgameCounts {
		camel := toCamelCase(ec.ID)
		sb.WriteString(fmt.Sprintf("\t%sEndgamePointsVal = %d\n", camel, ec.Points))
	}
	for _, status := range yamlData.Statuses {
		camel := toCamelCase(status.ID)
		if len(status.Values) >= 2 {
			for _, val := range status.Values {
				sb.WriteString(fmt.Sprintf("\t%s%sPointsVal = %d\n", camel, toCamelCase(val.ID), val.Points))
			}
		} else {
			sb.WriteString(fmt.Sprintf("\t%sPointsVal = %d\n", camel, status.Points))
		}
	}
	sb.WriteString(")\n\n")

	// ScoreSummary Struct
	sb.WriteString("type ScoreSummary struct {\n")
	for _, sc := range yamlData.ScoringCounts {
		sb.WriteString(fmt.Sprintf("\t%sPoints int\n", toCamelCase(sc.ID)))
	}
	for _, ec := range yamlData.EndgameCounts {
		sb.WriteString(fmt.Sprintf("\t%sPoints int\n", toCamelCase(ec.ID)))
	}
	for _, status := range yamlData.Statuses {
		sb.WriteString(fmt.Sprintf("\t%sPoints int\n", toCamelCase(status.ID)))
	}
	if len(yamlData.ScoringCounts)+len(yamlData.EndgameCounts)+len(yamlData.Statuses) > 0 {
		sb.WriteString("\n")
	}

	sb.WriteString("\tAutoPoints    int\n\tTeleopPoints  int\n\tEndgamePoints int\n\tMatchPoints   int\n\n\tFoulPoints int\n\n\tScore int\n\n\tPlayoffDq             bool\n\tNumOpponentMajorFouls int\n\n")

	for _, rp := range yamlData.RPs {
		sb.WriteString(fmt.Sprintf("\t%s bool\n", toCamelCase(rp.ID)+"RankingPoint"))
	}
	sb.WriteString("\tBonusRankingPoints int\n}\n\n")

	// Summarize function
	sb.WriteString("func (score *Score) Summarize(opponentScore *Score) *ScoreSummary {\n")
	sb.WriteString(`	summary := new(ScoreSummary)
	summary.PlayoffDq = score.PlayoffDq
	if score.PlayoffDq {
		return summary
	}

	var autoPoints int
	var teleopPoints int
	var endgamePoints int

`)

	// scoring_counts accumulation
	for _, sc := range yamlData.ScoringCounts {
		camel := toCamelCase(sc.ID)
		if sc.Phase == "auto" || sc.Phase == "both" {
			sb.WriteString(fmt.Sprintf("\tauto%s := score.Auto%sCount * %sAutoPointsVal\n", camel, camel, camel))
			sb.WriteString(fmt.Sprintf("\tautoPoints += auto%s\n", camel))
			sb.WriteString(fmt.Sprintf("\tsummary.%sPoints += auto%s\n", camel, camel))
		}
		if sc.Phase == "teleop" || sc.Phase == "both" {
			sb.WriteString(fmt.Sprintf("\tteleop%s := score.Teleop%sCount * %sTeleopPointsVal\n", camel, camel, camel))
			sb.WriteString(fmt.Sprintf("\tteleopPoints += teleop%s\n", camel))
			sb.WriteString(fmt.Sprintf("\tsummary.%sPoints += teleop%s\n", camel, camel))
		}
	}
	if len(yamlData.ScoringCounts) > 0 {
		sb.WriteString("\n")
	}

	// endgame_counts accumulation
	for _, ec := range yamlData.EndgameCounts {
		camel := toCamelCase(ec.ID)
		sb.WriteString(fmt.Sprintf("\tendgame%s := score.Endgame%sCount * %sEndgamePointsVal\n", camel, camel, camel))
		sb.WriteString(fmt.Sprintf("\tendgamePoints += endgame%s\n", camel))
		sb.WriteString(fmt.Sprintf("\tsummary.%sPoints = endgame%s\n", camel, camel))
	}
	if len(yamlData.EndgameCounts) > 0 {
		sb.WriteString("\n")
	}

	// statuses accumulation
	for _, status := range yamlData.Statuses {
		camel := toCamelCase(status.ID)
		var phaseVar string
		if status.Phase == "auto" {
			phaseVar = "autoPoints"
		} else {
			phaseVar = "endgamePoints"
		}

		if len(status.Values) >= 2 {
			sb.WriteString(fmt.Sprintf("\tfor _, v := range score.%sStatuses {\n", camel))
			sb.WriteString("\t\tswitch v {\n")
			for _, val := range status.Values {
				valConst := fmt.Sprintf("%s%s", camel, toCamelCase(val.ID))
				valPoints := fmt.Sprintf("%s%sPointsVal", camel, toCamelCase(val.ID))
				sb.WriteString(fmt.Sprintf("\t\tcase %s:\n", valConst))
				sb.WriteString(fmt.Sprintf("\t\t\tsummary.%sPoints += %s\n", camel, valPoints))
				sb.WriteString(fmt.Sprintf("\t\t\t%s += %s\n", phaseVar, valPoints))
			}
			sb.WriteString("\t\t}\n\t}\n")
		} else {
			sb.WriteString(fmt.Sprintf("\tfor _, v := range score.%sStatuses {\n\t\tif v {\n", camel))
			sb.WriteString(fmt.Sprintf("\t\t\tsummary.%sPoints += %sPointsVal\n", camel, camel))
			sb.WriteString(fmt.Sprintf("\t\t\t%s += %sPointsVal\n", phaseVar, camel))
			sb.WriteString("\t\t}\n\t}\n")
		}
	}
	if len(yamlData.Statuses) > 0 {
		sb.WriteString("\n")
	}

	sb.WriteString(`	summary.AutoPoints = autoPoints
	summary.TeleopPoints = teleopPoints
	summary.EndgamePoints = endgamePoints
	summary.MatchPoints = autoPoints + teleopPoints + endgamePoints

	for _, foul := range opponentScore.Fouls {
		summary.FoulPoints += foul.PointValue()
		if foul.IsMajor {
			summary.NumOpponentMajorFouls++
		}
	}
	summary.Score = summary.MatchPoints + summary.FoulPoints

`)

	// Ranking points computation
	for _, rp := range yamlData.RPs {
		camelRP := toCamelCase(rp.ID) + "RankingPoint"
		sb.WriteString(fmt.Sprintf("\tsummary.%s = %s(*score, *opponentScore)\n", camelRP, rp.LogicFunc))
		sb.WriteString(fmt.Sprintf("\tif summary.%s {\n\t\tsummary.BonusRankingPoints++\n\t}\n", camelRP))
	}

	sb.WriteString("\n\treturn summary\n}\n\n")

	// DetermineMatchStatus implementation
	sb.WriteString(`type MatchStatus int

const (
	MatchScheduled MatchStatus = iota
	MatchHidden
	RedWonMatch
	BlueWonMatch
	TieMatch
)

func (status MatchStatus) Get(redWins, blueWins, tie string) string {
	if status == RedWonMatch {
		return redWins
	} else if status == BlueWonMatch {
		return blueWins
	}
	return tie
}

func comparePoints(red, blue int) MatchStatus {
	if red > blue {
		return RedWonMatch
	} else if blue > red {
		return BlueWonMatch
	}
	return TieMatch
}

func DetermineMatchStatus(
	red, blue *ScoreSummary,
	applyPlayoffTiebreakers bool,
) (MatchStatus, string) {
	if red.PlayoffDq != blue.PlayoffDq {
		if red.PlayoffDq {
			return BlueWonMatch, ""
		}
		return RedWonMatch, ""
	}

	if status := comparePoints(red.Score, blue.Score); status != TieMatch {
		return status, ""
	}

	if applyPlayoffTiebreakers {
		if status := comparePoints(red.NumOpponentMajorFouls, blue.NumOpponentMajorFouls); status != TieMatch {
			return status, "TIEBREAK: MAJOR FOULS"
		}
`)

	for _, tb := range yamlData.PlayoffTiebreakers {
		var ownField, label string
		switch tb.Metric {
		case "auto_points":
			ownField = "AutoPoints"
			label = "AUTO POINTS"
		case "teleop_points":
			ownField = "TeleopPoints"
			label = "TELEOP POINTS"
		case "endgame_points":
			ownField = "EndgamePoints"
			label = "ENDGAME POINTS"
		case "total_points":
			ownField = "MatchPoints"
			label = "TOTAL POINTS"
		default:
			ownField = toCamelCase(tb.Metric) + "Points"
			// Find display name
			displayName := tb.Metric
			for _, sc := range yamlData.ScoringCounts {
				if sc.ID == tb.Metric {
					displayName = sc.DisplayName
				}
			}
			for _, ec := range yamlData.EndgameCounts {
				if ec.ID == tb.Metric {
					displayName = ec.DisplayName
				}
			}
			for _, s := range yamlData.Statuses {
				if s.ID == tb.Metric {
					displayName = s.DisplayName
				}
			}
			label = strings.ToUpper(displayName)
		}

		sb.WriteString(fmt.Sprintf("\t\tif status := comparePoints(red.%s, blue.%s); status != TieMatch {\n", ownField, ownField))
		sb.WriteString(fmt.Sprintf("\t\t\treturn status, %q\n", "TIEBREAK: "+label))
		sb.WriteString("\t\t}\n")
	}

	sb.WriteString(`		return TieMatch, "TRUE TIE"
	}

	return TieMatch, ""
}
`)

	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}
